apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gremlin
  namespace: gremlin
  labels:
    app: gremlin
spec:
  selector:
    matchLabels:
      app: gremlin
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
